package CapstoneDesign.Backendserver.domain;

public enum JobCategory {
    CONSULTING,MANAGEMENT,ADVERTISEMENT,PRODUCTION,REASEARCH_AND_DEVELOPEMENT,
    IT,SERVICE,CONSTRUCTION,LEARNING,DESIGN,MEDIA,ETC
}
